### ISSUE TITLE
Leaf faces not loading for Quake 3 BSPs

### ISSUE THREAD

**Issue by Panzerhandschuh** [wfowler1/LibBSP#5]
The FirstMarkFaceIndex and NumMarkFaceIndices properties are not loading properly for Quake 3 BSPs. It looks like there is a mistake in the code that checks for the map type (Leaf.cs):
```
MapType.IsSubtypeOf(MapType.Quake3) && MapType.IsSubtypeOf(MapType.CoD)
```

I'm not sure what the BSP file spec is for Call of Duty but I'm guessing this code is meant to check if the map type is Quake 3 **OR** Call of Duty.

**Comment by wfowler1** [comment]
Hah, you're right, that's pretty dumb. Actually CoD is completely different so I need to have a quick look over this struct.
